"""Fail-closed rendering of a sanitized Learning Pack Bundle."""

from __future__ import annotations

from dataclasses import dataclass
from hashlib import sha256
from html import escape
from typing import Any, Iterator

from .export_repository import ExportRepository
from .learning_bundle import LearningPackBundle


EXPORT_FORMAT_VERSION = 1
DEFAULT_MAX_EXPORT_BYTES = 2_000_000


class ExportError(RuntimeError):
    """Raised when a standalone artifact cannot be proven safe."""


@dataclass(frozen=True, slots=True)
class ExportPolicy:
    """Explicit evidence required before generated bytes may be committed."""

    forbidden_canaries: tuple[bytes, ...]
    max_export_bytes: int = DEFAULT_MAX_EXPORT_BYTES
    policy_version: int = 1

    def __post_init__(self) -> None:
        if self.policy_version != 1:
            raise ExportError("unsupported export policy version")
        if (
            not isinstance(self.forbidden_canaries, tuple)
            or not self.forbidden_canaries
            or any(
                not isinstance(canary, bytes) or not canary
                for canary in self.forbidden_canaries
            )
        ):
            raise ExportError("export requires at least one non-empty privacy canary")
        if len(set(self.forbidden_canaries)) != len(self.forbidden_canaries):
            raise ExportError("privacy canaries must be unique")
        if (
            not isinstance(self.max_export_bytes, int)
            or isinstance(self.max_export_bytes, bool)
            or self.max_export_bytes < 1
        ):
            raise ExportError("max_export_bytes must be a positive integer")

    @property
    def canary_digests(self) -> tuple[str, ...]:
        return tuple(
            sorted(sha256(canary).hexdigest() for canary in self.forbidden_canaries)
        )


@dataclass(frozen=True, slots=True)
class ExportReceipt:
    export_id: str
    artifact_sha256: str
    bundle_sha256: str
    accepted_snapshot_sha256: str
    relative_path: str
    canary_digests: tuple[str, ...]
    already_exists: bool
    files_scanned: int = 1
    privacy_status: str = "passed"
    schema_version: int = 1

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "status": "already_exists" if self.already_exists else "exported",
            "export_id": self.export_id,
            "artifact_sha256": self.artifact_sha256,
            "bundle_sha256": self.bundle_sha256,
            "accepted_snapshot_sha256": self.accepted_snapshot_sha256,
            "relative_path": self.relative_path,
            "files_scanned": self.files_scanned,
            "canary_digests": list(self.canary_digests),
            "privacy_status": self.privacy_status,
        }


class StandaloneExporter:
    """Render and atomically commit one portable HTML artifact."""

    def __init__(self, repository: ExportRepository) -> None:
        self.repository = repository

    def export(
        self,
        bundle: LearningPackBundle,
        policy: ExportPolicy,
    ) -> ExportReceipt:
        if not isinstance(bundle, LearningPackBundle):
            raise ExportError("export source must be a validated Learning Pack Bundle")
        if not isinstance(policy, ExportPolicy):
            raise ExportError("export policy does not match the schema")

        projection = _publishable_projection(bundle)
        _assert_canaries_absent(
            _logical_strings(projection),
            policy.forbidden_canaries,
        )
        rendered = _render_html(bundle)
        _assert_rendered_canaries_absent(rendered, policy.forbidden_canaries)
        if len(rendered) > policy.max_export_bytes:
            raise ExportError("standalone export exceeds its size limit")

        artifact_sha256 = sha256(rendered).hexdigest()
        export_id = f"export-{artifact_sha256[:20]}"
        commit = self.repository.commit(bundle.pack_id, export_id, rendered)
        relative_path = str(commit.path.relative_to(self.repository.root))
        visible = self.repository.read_committed(commit)
        if visible != rendered or sha256(visible).hexdigest() != artifact_sha256:
            raise ExportError("committed export bytes do not match their receipt")
        _assert_rendered_canaries_absent(visible, policy.forbidden_canaries)
        return ExportReceipt(
            export_id=export_id,
            artifact_sha256=artifact_sha256,
            bundle_sha256=bundle.bundle_sha256,
            accepted_snapshot_sha256=bundle.accepted_snapshot_sha256,
            relative_path=relative_path,
            canary_digests=policy.canary_digests,
            already_exists=commit.already_exists,
        )


def _publishable_projection(bundle: LearningPackBundle) -> dict[str, Any]:
    """Explicit allowlist: never serialize an implementation object wholesale."""

    return {
        "format_version": EXPORT_FORMAT_VERSION,
        "pack": {
            "pack_id": bundle.pack_id,
            "title": bundle.title,
            "version": bundle.pack_version,
            "bundle_sha256": bundle.bundle_sha256,
        },
        "concepts": [
            {
                "concept_id": concept.concept_id,
                "title": concept.title,
                "summary": concept.summary,
            }
            for concept in bundle.concepts
        ],
        "claims": [
            {
                "claim_id": claim.claim_id,
                "text": claim.text,
                "fact_status": claim.fact_status,
                "history_action": claim.history_action,
                "source_type": claim.provenance.source_type,
                "observed_at": claim.provenance.observed_at,
            }
            for claim in bundle.claims
        ],
        "lessons": [
            {
                "lesson_id": lesson.lesson_id,
                "lesson_revision_sha256": lesson.lesson_revision_sha256,
                "title": lesson.title,
                "concept_id": lesson.concept_id,
                "claim_id": lesson.claim_id,
                "outcome": {
                    "outcome_id": lesson.outcome.outcome_id,
                    "outcome_revision_sha256": (
                        lesson.outcome.outcome_revision_sha256
                    ),
                    "statement": lesson.outcome.statement,
                },
                "map_stages": [
                    {
                        "stage_id": stage.stage_id,
                        "title": stage.title,
                        "description": stage.description,
                    }
                    for stage in lesson.map_stages
                ],
                "prediction": {
                    "prompt": lesson.prediction.prompt,
                    "choices": [
                        {"choice_id": choice.choice_id, "text": choice.text}
                        for choice in lesson.prediction.choices
                    ],
                },
                "activity": {
                    "scenario_id": lesson.activity.scenario_id,
                    "instructions": lesson.activity.instructions,
                    "seed": lesson.activity.seed,
                    "input_revision_sha256": (
                        lesson.activity.input_revision_sha256
                    ),
                    "actions": [
                        {
                            "action_id": action.action_id,
                            "label": action.label,
                            "description": action.description,
                        }
                        for action in lesson.activity.actions
                    ],
                    "renderer_capabilities": list(
                        lesson.activity.renderer_capabilities
                    ),
                },
                "evidence": {
                    "claim": lesson.evidence.claim,
                    "cards": [
                        {
                            "evidence_id": card.evidence_id,
                            "title": card.title,
                            "proves": card.proves,
                            "does_not_prove": card.does_not_prove,
                            "source": card.source,
                            "scope": card.scope,
                            "sensitivity": card.sensitivity,
                            "observed_at": card.observed_at,
                        }
                        for card in lesson.evidence.cards
                    ],
                },
                "explanation": {
                    "prompt": lesson.explanation.prompt,
                    "minimum_characters": lesson.explanation.minimum_characters,
                    "qualification": {
                        "prompt": lesson.explanation.qualification.prompt,
                        "choices": [
                            {
                                "choice_id": choice.choice_id,
                                "text": choice.text,
                            }
                            for choice in lesson.explanation.qualification.choices
                        ],
                    },
                },
            }
            for lesson in bundle.lessons
        ],
    }


def _logical_strings(value: Any) -> Iterator[str]:
    if isinstance(value, str):
        yield value
    elif isinstance(value, dict):
        for key, child in value.items():
            yield key
            yield from _logical_strings(child)
    elif isinstance(value, list):
        for child in value:
            yield from _logical_strings(child)


def _assert_canaries_absent(
    strings: Iterator[str],
    canaries: tuple[bytes, ...],
) -> None:
    encoded_strings = tuple(text.encode("utf-8") for text in strings)
    for canary in canaries:
        if any(canary in text for text in encoded_strings):
            raise ExportError("publishable content contains a configured privacy canary")


def _assert_rendered_canaries_absent(
    rendered: bytes,
    canaries: tuple[bytes, ...],
) -> None:
    for canary in canaries:
        if canary in rendered:
            raise ExportError("standalone export contains a configured privacy canary")
        try:
            escaped = escape(canary.decode("utf-8"), quote=True).encode("utf-8")
        except UnicodeDecodeError:
            continue
        if escaped and escaped in rendered:
            raise ExportError(
                "standalone export contains an escaped configured privacy canary"
            )


def _render_html(bundle: LearningPackBundle) -> bytes:
    projection = _publishable_projection(bundle)
    pack = projection["pack"]
    concepts = "".join(
        "<article>"
        f"<h3>{escape(concept['title'])}</h3>"
        f"<p>{escape(concept['summary'])}</p>"
        "</article>"
        for concept in projection["concepts"]
    )
    claims = "".join(
        "<article>"
        f"<h3>{escape(claim['fact_status'].title())} fact</h3>"
        f"<p>{escape(claim['text'])}</p>"
        "<dl>"
        f"<dt>Source type</dt><dd>{escape(claim['source_type'])}</dd>"
        f"<dt>Observed</dt><dd>{escape(claim['observed_at'])}</dd>"
        "</dl>"
        "</article>"
        for claim in projection["claims"]
    )
    lesson_identities = "".join(
        "<article>"
        f"<h3>{escape(lesson['title'])}</h3>"
        "<dl>"
        f"<dt>Lesson revision</dt><dd><code>{escape(lesson['lesson_revision_sha256'])}</code></dd>"
        f"<dt>Outcome revision</dt><dd><code>{escape(lesson['outcome']['outcome_revision_sha256'])}</code></dd>"
        f"<dt>Activity input revision</dt><dd><code>{escape(lesson['activity']['input_revision_sha256'])}</code></dd>"
        "</dl>"
        "</article>"
        for lesson in projection["lessons"]
    )
    lessons = "".join(_render_lesson(lesson) for lesson in projection["lessons"])
    document = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'">
<title>{escape(pack["title"])} · Learning Pack</title>
<style>
:root {{ color-scheme: light dark; font-family: system-ui, sans-serif; line-height: 1.5; }}
body {{ max-width: 64rem; margin: 0 auto; padding: 1.5rem; }}
section, article {{ margin-block: 1.5rem; }}
.map {{ display: grid; gap: 1rem; grid-template-columns: repeat(auto-fit,minmax(12rem,1fr)); }}
.card {{ border: 1px solid; border-radius: .4rem; padding: 1rem; }}
.skip-link {{ position: absolute; left: -10000px; }}
.skip-link:focus {{ position: static; }}
dt {{ font-weight: 700; }}
</style>
</head>
<body>
<a class="skip-link" href="#content">Skip to learning content</a>
<header>
<p>Standalone reviewed Learning Pack</p>
<h1>{escape(pack["title"])}</h1>
<p>Pack version {pack["version"]}</p>
</header>
<main id="content" tabindex="-1">
<section id="artifact-identity" aria-labelledby="identity">
<h2 id="identity">Reviewed artifact identity</h2>
<dl>
<dt>Learning Pack Bundle</dt><dd><code>{escape(bundle.bundle_sha256)}</code></dd>
<dt>Accepted Pack snapshot</dt><dd><code>{escape(bundle.accepted_snapshot_sha256)}</code></dd>
</dl>
{lesson_identities}
</section>
<section aria-labelledby="concepts"><h2 id="concepts">Concepts</h2>{concepts}</section>
<section aria-labelledby="facts"><h2 id="facts">Accepted facts</h2>{claims}</section>
{lessons}
</main>
</body>
</html>
"""
    return document.encode("utf-8")


def _render_lesson(lesson: dict[str, Any]) -> str:
    stages = "".join(
        '<article class="card">'
        f"<h3>{escape(stage['title'])}</h3>"
        f"<p>{escape(stage['description'])}</p>"
        "</article>"
        for stage in lesson["map_stages"]
    )
    prediction_choices = "".join(
        f"<li>{escape(choice['text'])}</li>"
        for choice in lesson["prediction"]["choices"]
    )
    actions = "".join(
        "<li>"
        f"<strong>{escape(action['label'])}</strong>: "
        f"{escape(action['description'])}"
        "</li>"
        for action in lesson["activity"]["actions"]
    )
    evidence = "".join(
        '<article class="card">'
        f"<h4>{escape(card['title'])}</h4>"
        f"<p><strong>Proves:</strong> {escape(card['proves'])}</p>"
        f"<p><strong>Does not prove:</strong> {escape(card['does_not_prove'])}</p>"
        f"<p><strong>Source:</strong> {escape(card['source'])}</p>"
        f"<p><strong>Scope:</strong> {escape(card['scope'])}</p>"
        f"<p><strong>Sensitivity:</strong> {escape(card['sensitivity'])}</p>"
        f"<p><strong>Observed:</strong> {escape(card['observed_at'])}</p>"
        "</article>"
        for card in lesson["evidence"]["cards"]
    )
    return (
        f'<section aria-labelledby="{escape(lesson["lesson_id"])}">'
        f'<h2 id="{escape(lesson["lesson_id"])}">{escape(lesson["title"])}</h2>'
        f"<p><strong>Outcome:</strong> {escape(lesson['outcome']['statement'])}</p>"
        "<h3>Map</h3>"
        f'<div class="map">{stages}</div>'
        "<h3>Predict</h3>"
        f"<p>{escape(lesson['prediction']['prompt'])}</p>"
        f"<ol>{prediction_choices}</ol>"
        "<h3>Try</h3>"
        f"<p>{escape(lesson['activity']['instructions'])}</p>"
        f"<ul>{actions}</ul>"
        "<h3>Prove</h3>"
        f"<p>{escape(lesson['evidence']['claim'])}</p>"
        f'<div class="map">{evidence}</div>'
        "<h3>Explain</h3>"
        f"<p>{escape(lesson['explanation']['prompt'])}</p>"
        "<h4>Check your explanation</h4>"
        f"<p>{escape(lesson['explanation']['qualification']['prompt'])}</p>"
        "<ul>"
        + "".join(
            f"<li>{escape(choice['text'])}</li>"
            for choice in lesson["explanation"]["qualification"]["choices"]
        )
        + "</ul>"
        "</section>"
    )
