"""Write-only capability for deterministic standalone exports."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re
from threading import RLock

from ._bound_directory import _BoundDirectory
from .domain import PACK_ID_PATTERN
from .storage import StorageError


EXPORT_ID_PATTERN = re.compile(r"^export-[0-9a-f]{20}$")
_EXPORT_LOCK = RLock()


class UncertainExportCommit(StorageError):
    """The replacement happened but its visible bytes cannot be proven."""


@dataclass(frozen=True, slots=True)
class ExportCommit:
    path: Path
    already_exists: bool


class ExportRepository:
    """Commit generated bytes under one safe export root."""

    def __init__(self, directory: _BoundDirectory) -> None:
        self._directory = directory
        self.root = directory.path

    @classmethod
    def open(cls, root: Path) -> ExportRepository:
        return cls(_BoundDirectory.open(root, "exports directory"))

    def commit(
        self,
        pack_id: str,
        export_id: str,
        content: bytes,
    ) -> ExportCommit:
        if not isinstance(pack_id, str) or not PACK_ID_PATTERN.fullmatch(pack_id):
            raise StorageError("export pack_id does not match the schema")
        if (
            not isinstance(export_id, str)
            or not EXPORT_ID_PATTERN.fullmatch(export_id)
        ):
            raise StorageError("export_id does not match the schema")
        if not isinstance(content, bytes) or not content:
            raise StorageError("export content must be non-empty bytes")

        leaf = f"{pack_id}--{export_id}.html"
        path = self.root / leaf
        with _EXPORT_LOCK:
            existing = self._directory.read_regular(leaf, "export target")
            if existing is not None:
                if existing != content:
                    raise StorageError(
                        "export identity collides with different content"
                    )
                return ExportCommit(path, True)

            outcome = self._directory.atomic_replace(leaf, content, 0o644)
            if outcome.directory_synced:
                return ExportCommit(path, False)
            try:
                visible = self._directory.read_regular(leaf, "export target")
            except (OSError, StorageError) as exc:
                raise UncertainExportCommit(
                    "export replacement happened but its visible state is uncertain"
                ) from exc
            if visible != content:
                raise UncertainExportCommit(
                    "export replacement happened but intended bytes are not visible"
                )
            return ExportCommit(path, False)

    def read_committed(self, commit: ExportCommit) -> bytes:
        """Re-read committed bytes without following a replaced target."""
        if (
            not isinstance(commit, ExportCommit)
            or commit.path.parent != self.root
        ):
            raise StorageError("export commit does not belong to this repository")
        visible = self._directory.read_regular(
            commit.path.name,
            "export target",
        )
        if visible is None:
            raise StorageError("export target is missing")
        return visible

    def close(self) -> None:
        self._directory.close()

    def __enter__(self) -> ExportRepository:
        return self

    def __exit__(self, *_: object) -> None:
        self.close()
