"""Write-only capability for deterministic standalone exports."""

from __future__ import annotations

from dataclasses import dataclass
import os
from pathlib import Path
import re
import stat

from .domain import PACK_ID_PATTERN
from .storage import StorageError, _read_confined_regular_file, _write_atomic


EXPORT_ID_PATTERN = re.compile(r"^export-[0-9a-f]{20}$")


class UncertainExportCommit(StorageError):
    """The replacement happened but its visible bytes cannot be proven."""


@dataclass(frozen=True, slots=True)
class ExportCommit:
    path: Path
    already_exists: bool


class ExportRepository:
    """Commit generated bytes under one safe export root."""

    def __init__(self, root: Path) -> None:
        self.root = root

    @classmethod
    def open(cls, root: Path) -> ExportRepository:
        if root.is_symlink() or not root.is_dir():
            raise StorageError("exports directory is missing or unsafe")
        resolved = root.resolve(strict=True)
        metadata = resolved.stat()
        if hasattr(os, "getuid") and metadata.st_uid != os.getuid():
            raise StorageError("exports directory is not owned by the current user")
        if metadata.st_mode & 0o022:
            raise StorageError("exports directory cannot be group or world writable")
        return cls(resolved)

    def commit(
        self,
        pack_id: str,
        export_id: str,
        content: bytes,
    ) -> ExportCommit:
        self._require_safe_root()
        if not isinstance(pack_id, str) or not PACK_ID_PATTERN.fullmatch(pack_id):
            raise StorageError("export pack_id does not match the schema")
        if (
            not isinstance(export_id, str)
            or not EXPORT_ID_PATTERN.fullmatch(export_id)
        ):
            raise StorageError("export_id does not match the schema")
        if not isinstance(content, bytes) or not content:
            raise StorageError("export content must be non-empty bytes")

        path = self.root / f"{pack_id}--{export_id}.html"
        if path.is_symlink():
            raise StorageError("export target cannot be a symbolic link")
        if path.exists():
            existing = _read_confined_regular_file(path, self.root, "export target")
            if existing != content:
                raise StorageError("export identity collides with different content")
            return ExportCommit(path, True)

        outcome = _write_atomic(path, content, 0o644)
        if outcome.directory_synced:
            return ExportCommit(path, False)
        try:
            visible = _read_confined_regular_file(path, self.root, "export target")
        except (OSError, StorageError) as exc:
            raise UncertainExportCommit(
                "export replacement happened but its visible state is uncertain"
            ) from exc
        if visible != content:
            raise UncertainExportCommit(
                "export replacement happened but intended bytes are not visible"
            )
        return ExportCommit(path, False)

    def read_committed(self, commit: ExportCommit) -> bytes:
        """Re-read committed bytes without following a replaced target."""
        self._require_safe_root()
        if (
            not isinstance(commit, ExportCommit)
            or commit.path.parent != self.root
            or commit.path.is_symlink()
        ):
            raise StorageError("export commit does not belong to this repository")
        return _read_confined_regular_file(
            commit.path,
            self.root,
            "export target",
        )

    def _require_safe_root(self) -> None:
        if self.root.is_symlink() or not self.root.is_dir():
            raise StorageError("exports directory is missing or unsafe")
        metadata = self.root.stat()
        if not stat.S_ISDIR(metadata.st_mode):
            raise StorageError("exports directory is missing or unsafe")
        if hasattr(os, "getuid") and metadata.st_uid != os.getuid():
            raise StorageError("exports directory is not owned by the current user")
        if metadata.st_mode & 0o022:
            raise StorageError("exports directory cannot be group or world writable")
